import { T_Config } from './ConfigBase';
export type TArg = {
    ':タグ名'?: string;
    canskip?: boolean;
    layer?: string;
    class?: string;
    index?: number;
    dive?: string;
    page?: string;
    alpha?: number;
    pivot_x?: number;
    pivot_y?: number;
    rotation?: number;
    scale_x?: number;
    scale_y?: number;
    visible?: boolean;
    blendmode?: string;
    left?: number;
    top?: number;
    width?: number;
    height?: number;
    pl?: number;
    pr?: number;
    pt?: number;
    pb?: number;
    rotate?: number;
    in_style?: string;
    out_style?: string;
    ffs?: string;
    noffs?: string;
    kinsoku_sol?: string;
    kinsoku_eol?: string;
    kinsoku_dns?: string;
    kinsoku_bura?: string;
    bura?: boolean;
    break_fixed?: boolean;
    break_fixed_left?: number;
    break_fixed_top?: number;
    time?: number;
    rule?: string;
    glsl?: string;
    render?: boolean;
    pos?: string;
    text?: string;
    wait?: number;
    record?: boolean;
    pic?: string;
    enabled?: boolean;
    hint?: string;
    hint_style?: string;
    hint_opt?: string;
    clickse?: string;
    enterse?: string;
    leavese?: string;
    clicksebuf?: string;
    entersebuf?: string;
    leavesebuf?: string;
    onenter?: string;
    onleave?: string;
    t?: string;
    r?: string;
    exp?: string;
    char?: string;
    sesame?: string;
    cast?: string;
    val?: string;
    flags?: string;
    reg?: string;
    len?: string;
    url?: string;
    format?: string;
    chain?: string;
    path?: string;
    fn?: string;
    face?: string;
    label?: string;
    call?: boolean;
    global?: boolean;
    name?: string;
    clear_local_event?: boolean;
    style?: string;
    style_hover?: string;
    style_clicked?: string;
    r_style?: string;
    r_style_hover?: string;
    r_style_clicked?: string;
    r_align?: string;
    b_width?: string;
    b_height?: string;
    b_color?: string;
    b_alpha?: number;
    b_alpha_isfixed?: boolean;
    b_pic?: string;
    back_clear?: string;
    max_col?: string;
    max_row?: string;
    bura_col?: string;
    chk_overrow?: string;
    dx?: number;
    dy?: number;
    key?: string;
    type?: string;
    camera_target?: string;
    arg?: TArg;
    fnc?: () => void;
    filter?: string;
    matrix?: string;
    clear_filter?: boolean;
    enable_filter?: boolean;
    ease?: string;
    centering?: boolean;
    x?: number | string;
    y?: number | string;
    id?: string;
    src?: string;
    var_name?: string;
    set_fnc?: string;
    break_fnc?: string;
    from?: number;
    to?: number | string;
    place?: number;
    add?: string;
    del?: string;
    buf?: string;
    buf2?: string;
    loop?: boolean;
    volume?: number;
    ret_ms?: number;
    end_ms?: number;
    join?: boolean;
    do_rec?: boolean;
    pan?: number;
    stop?: boolean;
    clear?: boolean;
    ':id_dc'?: string;
    ':id_tag'?: string;
    ':path'?: string;
    ':ln'?: number;
    ':col_s'?: number;
    ':col_e'?: number;
    ':idx_tkn'?: number;
    ':token'?: string;
    ':redraw'?: boolean;
    design_unit?: boolean;
};
export type TTag = (hArg: TArg) => boolean;
export type T_HTag = {
    clearsysvar: TTag;
    clearvar: TTag;
    let_abs: TTag;
    let_char_at: TTag;
    let_index_of: TTag;
    let_length: TTag;
    let_ml: TTag;
    let_replace: TTag;
    let_round: TTag;
    let_search: TTag;
    let_substr: TTag;
    let: TTag;
    add_lay: TTag;
    clear_lay: TTag;
    finish_trans: TTag;
    lay: TTag;
    trans: TTag;
    wt: TTag;
    add_filter: TTag;
    clear_filter: TTag;
    enable_filter: TTag;
    pause_tsy: TTag;
    resume_tsy: TTag;
    stop_tsy: TTag;
    tsy: TTag;
    wait_tsy: TTag;
    autowc: TTag;
    ch: TTag;
    ch_in_style: TTag;
    ch_out_style: TTag;
    clear_text: TTag;
    current: TTag;
    endlet_ml: TTag;
    endlink: TTag;
    er: TTag;
    graph: TTag;
    link: TTag;
    r: TTag;
    rec_ch: TTag;
    rec_r: TTag;
    reset_rec: TTag;
    ruby2: TTag;
    set_focus: TTag;
    span: TTag;
    tcy: TTag;
    add_face: TTag;
    wv: TTag;
    add_frame: TTag;
    frame: TTag;
    let_frame: TTag;
    set_frame: TTag;
    tsy_frame: TTag;
    clear_event: TTag;
    enable_event: TTag;
    event: TTag;
    l: TTag;
    p: TTag;
    s: TTag;
    set_cancel_skip: TTag;
    wait: TTag;
    waitclick: TTag;
    fadebgm: TTag;
    fadeoutbgm: TTag;
    fadeoutse: TTag;
    fadese: TTag;
    playbgm: TTag;
    playse: TTag;
    stop_allse: TTag;
    stopbgm: TTag;
    stopfadese: TTag;
    stopse: TTag;
    volume: TTag;
    wb: TTag;
    wf: TTag;
    wl: TTag;
    ws: TTag;
    xchgbuf: TTag;
    else: TTag;
    elsif: TTag;
    endif: TTag;
    if: TTag;
    button: TTag;
    call: TTag;
    jump: TTag;
    page: TTag;
    pop_stack: TTag;
    return: TTag;
    bracket2macro: TTag;
    char2macro: TTag;
    endmacro: TTag;
    macro: TTag;
    copybookmark: TTag;
    erasebookmark: TTag;
    load: TTag;
    record_place: TTag;
    reload_script: TTag;
    save: TTag;
    quake: TTag;
    stop_quake: TTag;
    wq: TTag;
    close: TTag;
    export: TTag;
    import: TTag;
    loadplugin: TTag;
    navigate_to: TTag;
    snapshot: TTag;
    title: TTag;
    toggle_full_screen: TTag;
    update_check: TTag;
    window: TTag;
    dump_lay: TTag;
    dump_script: TTag;
    dump_stack: TTag;
    dump_val: TTag;
    log: TTag;
    trace: TTag;
};
export type Script = {
    aToken: string[];
    len: number;
    aLNum: number[];
};
export declare const REG_TAG: RegExp;
export declare function tagToken2Name_Args(token: string): [name: string, args: string];
export declare function tagToken2Name(token: string): string;
export declare function splitAmpersand(token: string): {
    name: string;
    text: string;
    cast?: string;
};
export declare class Grammar {
    #private;
    private readonly cfg;
    constructor(cfg: T_Config);
    setEscape(ce: string): void;
    bracket2macro(hArg: TArg, hTag: T_HTag, scr: Script, start_idx: number): void;
    char2macro(hArg: TArg, hTag: T_HTag, scr: Script, start_idx: number): void;
    addC2M(a: string, b: string): void;
    resolveScript(txt: string): Script;
    testTagLetml(tkn: string): boolean;
    testTagEndLetml(tkn: string): boolean;
    testNoTxt(ch: string): boolean;
}
//# sourceMappingURL=Grammar.d.ts.map