import { T_HTag, TTag } from './Grammar';
import { T_Variable, T_SysBase, T_Data4Vari, T_LayerFactory, T_Main, T_Fire, T_FncHook, T_SysBaseLoadedParams, T_HPlugin, T_H_TMP_DATA } from './CmnInterface';
import { EventListenerCtn } from './EventListenerCtn';
import { T_Config, T_SysRoots, T_HSysBaseArg } from './ConfigBase';
import { Main } from './Main';
import { Application, Loader } from 'pixi.js';
export declare class SysBase implements T_SysRoots, T_SysBase {
    #private;
    private readonly hPlg;
    arg: T_HSysBaseArg;
    protected readonly elc: EventListenerCtn;
    hFactoryCls: {
        [cls: string]: T_LayerFactory;
    };
    constructor(hPlg: T_HPlugin | undefined, arg: T_HSysBaseArg);
    destroy(): void;
    protected loaded(...[hPlg,]: T_SysBaseLoadedParams): Promise<void | undefined>;
    protected main: Main | undefined;
    protected cfg: T_Config;
    setMain(main: Main, cfg: T_Config): void;
    protected run(): Promise<void>;
    stop(): void;
    fetch: (url: string, init?: RequestInit) => Promise<Response>;
    protected readonly data: T_Data4Vari;
    initVal(_hTmp: T_H_TMP_DATA, _comp: (data: T_Data4Vari) => void): Promise<void>;
    flush(): void;
    protected flushSub(): void;
    protected val: T_Variable;
    init(hTag: T_HTag, appPixi: Application, val: T_Variable): Promise<void>[];
    get cvsWidth(): number;
    get cvsHeight(): number;
    get cvsScale(): number;
    get ofsLeft4elm(): number;
    get ofsTop4elm(): number;
    get ofsPadLeft_Dom2PIXI(): number;
    get ofsPadTop_Dom2PIXI(): number;
    protected isFullScr: boolean;
    cvsResize(): void;
    use4ViteElectron(_src: string, _path: string, _ld: Loader, _main: T_Main): boolean;
    attach_debug(main: T_Main): void;
    protected extPort: number;
    end(): void;
    protected toast(nm: string): void;
    pathBaseCnvSnPath4Dbg: string;
    protected fire: T_Fire;
    setFire(fire: T_Fire): void;
    addHook(fnc: T_FncHook): void;
    callHook: T_FncHook;
    send2Dbg: T_FncHook;
    copyBMFolder: (_from: number, _to: number) => void;
    eraseBMFolder: (_place: number) => void;
    protected readonly close: TTag;
    protected readonly _export: TTag;
    protected readonly _import: TTag;
    protected readonly navigate_to: TTag;
    protected readonly title: TTag;
    protected titleSub(_txt: string): void;
    static tglFlscr_HdrErr(e: unknown): void;
    static modKey(e: KeyboardEvent): string;
    protected tglFlscr_sub(): Promise<void>;
    protected readonly update_check: TTag;
    protected readonly window: TTag;
    setTitleInfo(txt: string): void;
    dec: (_ext: string, tx: string) => Promise<string>;
    decAB(iab: ArrayBuffer): Promise<HTMLImageElement | HTMLVideoElement | ArrayBuffer>;
    protected enc: (tx: string) => Promise<string>;
    protected stk: () => string;
    hash: (_str: string) => string;
    readonly isApp: boolean;
    protected $path_downloads: string;
    get path_downloads(): string;
    protected $path_userdata: string;
    get path_userdata(): string;
    capturePage(_path: string, _w: number, _h: number, _fnc: () => void): void;
    savePic(_path: string, _data_url: string): Promise<void>;
    ensureFile(_path: string): Promise<void>;
    appendFile(_path: string, _data: string): Promise<void>;
    outputFile(_path: string, _data: string): Promise<void>;
}
//# sourceMappingURL=SysBase.d.ts.map