import { IEvtMng } from './CmnLib';
import { HArg, IHTag, IVariable, IMain, IHEvt2Fnc } from './CmnInterface';
import { LayerMng } from './LayerMng';
import { ScriptIterator } from './ScriptIterator';
import { EventListenerCtn } from './EventListenerCtn';
import { DisplayObject, Application } from 'pixi.js';
import { SoundMng } from './SoundMng';
import { Config } from './Config';
import { SysBase } from './SysBase';
export declare class EventMng implements IEvtMng {
    private readonly cfg;
    private readonly hTag;
    private readonly appPixi;
    private readonly main;
    private readonly layMng;
    private readonly val;
    private readonly sndMng;
    private readonly scrItr;
    readonly sys: SysBase;
    private readonly elc;
    private ham;
    private readonly hHamEv;
    constructor(cfg: Config, hTag: IHTag, appPixi: Application, main: IMain, layMng: LayerMng, val: IVariable, sndMng: SoundMng, scrItr: ScriptIterator, sys: SysBase);
    resvFlameEvent(win: Window): void;
    private resvFlameEvent4Wheel;
    private ev_keydown;
    private ev_contextmenu;
    private ev_wheel;
    private wheeling;
    private extend_wheel;
    private ev_wheel_waitstop;
    destroy(): void;
    private hLocalEvt2Fnc;
    private hGlobalEvt2Fnc;
    fire(KEY: string, e: Event): void;
    private isWait;
    popLocalEvts(): IHEvt2Fnc;
    pushLocalEvts(h: IHEvt2Fnc): void;
    stdWait(fnc: () => void, canskip?: boolean): void;
    private procHook;
    private isDbgBreak;
    button(hArg: HArg, em: DisplayObject): void;
    waitCustomEvent(hArg: HArg, elc: EventListenerCtn, fnc: () => void): void;
    private waitCustomEvent4Wheel;
    private clear_event;
    private clear_eventer;
    private event;
    private getHtmlElmList;
    private goTxt;
    private l;
    private p;
    private fncCancelSkip;
    private set_cancel_skip;
    private unregisterClickEvts;
    private wait;
    isSkipKeyDown(): boolean;
    private readonly hDownKeys;
}
//# sourceMappingURL=EventMng.d.ts.map