import { Layer } from './Layer';
import { IEvtMng } from './CmnLib';
import { IVariable, IHTag, HArg, IMain } from './CmnInterface';
import { IInfTxLay } from './TxtStage';
import { Config } from './Config';
import { IMakeDesignCast } from './LayerMng';
import { Renderer } from 'pixi.js';
export declare class TxtLayer extends Layer {
    #private;
    static init(cfg: Config, hTag: IHTag, val: IVariable, recText: (txt: string) => void, isPageFore: (me: TxtLayer) => boolean): void;
    static setEvtMng(main: IMain, evtMng: IEvtMng): void;
    constructor();
    destroy(): void;
    set name(nm: string);
    get name(): string;
    cvsResize(): void;
    cvsResizeChildren(): void;
    lay(hArg: HArg): boolean;
    get width(): number;
    get height(): number;
    chgBackAlpha(g_alpha: number): void;
    static chgDoRec(doRec: boolean): void;
    static rec: (tx: string) => string;
    isCur: boolean;
    private mkStyle_r_align;
    tagCh(text: string): void;
    readonly click: () => boolean;
    clearText(): void;
    get pageText(): string;
    get enabled(): boolean;
    set enabled(e: boolean);
    readonly addButton: (hArg: HArg) => Promise<void>;
    canFocus(): boolean;
    clearLay(hArg: HArg): void;
    readonly record: () => {
        name: string;
        idx: number;
        alpha: number;
        blendMode: import("pixi.js").BLEND_MODES;
        rotation: number;
        scale_x: number;
        scale_y: number;
        pivot_x: number;
        pivot_y: number;
        x: number;
        y: number;
        visible: boolean;
    } & {
        enabled: boolean;
        r_align: string;
        b_do: string | null;
        b_pic: string;
        b_color: number;
        b_alpha: number;
        b_alpha_isfixed: boolean;
        ffs: string;
        txs: {
            infTL: IInfTxLay;
            cssText: string;
            left: number;
            idc_hArg: HArg;
            ch_filter: any[] | null;
            fi_easing: string;
            fo_easing: string;
        };
        strNoFFS: string;
        btns: string[];
    };
    playback(hLay: any, aPrm: Promise<void>[]): void;
    snapshot(rnd: Renderer, re: () => void): void;
    snapshot_end(): void;
    makeDesignCast(gdc: IMakeDesignCast): void;
    makeDesignCastChildren(gdc: IMakeDesignCast): void;
    showDesignCast(): void;
    showDesignCastChildren(): void;
    dump(): string;
}
//# sourceMappingURL=TxtLayer.d.ts.map