import { IEvtMng } from './CmnLib';
import { HArg } from './CmnInterface';
import { Config } from './Config';
import { IMakeDesignCast } from './LayerMng';
import { Container, Sprite, Renderer } from 'pixi.js';
export interface IInfTxLay {
    fontsize: number;
    $width: number;
    $height: number;
    pad_left: number;
    pad_right: number;
    pad_top: number;
    pad_bottom: number;
}
export declare class TxtStage extends Container {
    private infTL;
    private readonly spLay;
    private readonly canFocus;
    private static cfg;
    private static cvs;
    static init(cfg: Config): void;
    private static evtMng;
    static setEvtMng(evtMng: IEvtMng): void;
    static destroy(): void;
    private htmTxt;
    private readonly cntTxt;
    private readonly grpDbgMasume;
    private readonly idc;
    private readonly idcCh;
    getInfTL(): IInfTxLay;
    constructor(infTL: IInfTxLay, spLay: Sprite, canFocus: () => boolean);
    lay(hArg: HArg): void;
    private lay_sub;
    cvsResize(): void;
    private left;
    private isTategaki;
    get tategaki(): boolean;
    private padTx4x;
    private padTx4y;
    getWidth(): number;
    getHeight(): number;
    setSize(width: number, height: number): void;
    private static hWarning;
    private htm2tx;
    private ch_filter;
    private aSpTw;
    private aRect;
    private lenHtmTxt;
    private static reg行頭禁則;
    private static reg行末禁則;
    private static reg分割禁止;
    goTxt(aSpan: string[]): void;
    private beforeHTMLElm;
    private rctm;
    private readonly regDs;
    private fncEndChIn;
    private spWork;
    private isChInIng;
    skipChIn(): boolean;
    private static hChInStyle;
    private static readonly REG_NG_CHSTYLE_NAME_CHR;
    static initChStyle(): void;
    static getChInStyle(name: string): any;
    static ch_in_style(hArg: HArg): any;
    private static hChOutStyle;
    static getChOutStyle(name: string): {
        wait: number;
        alpha: number;
        x: string;
        y: string;
        nx: number;
        ny: number;
        scale_x: number;
        scale_y: number;
        rotate: number;
        join: boolean;
        ease: string;
    };
    static ch_out_style(hArg: HArg): any;
    private static cntBreak;
    dispBreak(pic: string): void;
    static delBreak(): void;
    private lh_half;
    private getChRects;
    private fi_easing;
    private fo_easing;
    private clearText;
    reNew(): TxtStage;
    record(): {
        infTL: IInfTxLay;
        cssText: string;
        left: number;
        idc_hArg: HArg;
        ch_filter: any[] | null;
        fi_easing: string;
        fo_easing: string;
    };
    playback(hLay: any): void;
    private sss;
    snapshot(rnd: Renderer, re: () => void): void;
    snapshot_end(): void;
    makeDesignCast(gdc: IMakeDesignCast): void;
    showDesignCast(): void;
    dump(): string;
    destroy(): void;
}
//# sourceMappingURL=TxtStage.d.ts.map