import { Container, Renderer } from 'pixi.js';
import { IEvtMng } from './CmnLib';
import { HArg } from './CmnInterface';
import { Config } from './Config';
export interface IInfTxLay {
    fontsize: number;
    $width: number;
    $height: number;
    pad_left: number;
    pad_right: number;
    pad_top: number;
    pad_bottom: number;
}
export declare class TxtStage extends Container {
    private infTL;
    private static cfg;
    private static cvs;
    static init(cfg: Config): void;
    private static evtMng;
    static setEvtMng(evtMng: IEvtMng): void;
    private htmTxt;
    private cntTxt;
    private grpDbgMasume;
    constructor(infTL: IInfTxLay, cnt: Container);
    lay(hArg: HArg): void;
    private lay_sub;
    private left;
    private isTategaki;
    private padTx4x;
    private padTx4y;
    private rctBoundCli;
    setSize(width: number, height: number): void;
    private static readonly hWarning;
    goTxt(aSpan: string[], layname: string): void;
    private goTxt2;
    private cntGoTxtSerializer;
    private goTxt2_htm;
    private htm2tx;
    private goTxt3;
    private static readonly REG_SURROGATE;
    private aRect;
    private ch_filter;
    private xz4htm2rect;
    private aSpTw;
    private static fncChkSkip;
    private goTxt3_tx2sp;
    goTxt_next(aSpan: string[], layname: string, delay: number): void;
    private rctm;
    private spWork;
    private putBreakMark2;
    private static cntBreak;
    dispBreak(pic: string): void;
    static delBreak(): void;
    private putBreakMark;
    private lh_half;
    private getChRects;
    skipFI(): boolean;
    private ch_anime_time_仮;
    private ch_slide_x;
    private fncFi;
    private fi_easing;
    private fo;
    private fo_easing;
    private clearText;
    passBaton(): TxtStage;
    record(): {
        infTL: IInfTxLay;
        cssText: string;
        left: number;
        ch_filter: any[] | null;
        fi_easing: string;
        fo: {
            alpha: number;
            x: string;
        };
        fo_easing: string;
        ch_anime_time_仮: number;
    };
    playback(hLay: any): void;
    snapshot(rnd: Renderer, re: () => void): void;
    static snapshotBreak(rnd: Renderer): void;
    dump(): string;
    destroy(): void;
}
