import { IHTag, IVariable, ISetVal, typeProcVal, ISysBase, IMark } from './CmnInterface';
import { Config } from './Config';
import { Areas } from './Areas';
export declare class Variable implements IVariable {
    private cfg;
    private hScope;
    private hSave;
    private hTmp;
    constructor(cfg: Config, hTag: IHTag);
    private data;
    private hSys;
    private hAreaKidoku;
    setSys(sys: ISysBase): void;
    private flush_;
    flush(): void;
    defTmp(name: string, fnc: typeProcVal): void;
    cloneMp(): object;
    setMp(mp: object): void;
    setMark(place: number, mark: IMark): void;
    getMark: (place: number) => IMark;
    cloneSave(): object;
    mark2save(mark: IMark): void;
    loadScrWork(fn: string): void;
    getAreaKidoku: (fn: string) => Areas;
    saveKidoku(): void;
    private copybookmark;
    private erasebookmark;
    private let;
    private let_abs;
    private let_char_at;
    private let_index_of;
    private let_length;
    private let_replace;
    private let_round;
    private let_search;
    private let_substr;
    private clearsysvar;
    private clearvar;
    private setVal;
    setVal_Nochk(scope: string, nm: string, val: any, autocast?: boolean): void;
    getVal: (arg_name: string, def?: string | number | undefined) => any;
    private castAuto;
    private REG_NUMERICLITERAL;
    private dump_val;
    private hValTrg;
    defValTrg(name: string, fnc: ISetVal): void;
    private runFirst_Bool_hSysVal_true;
    private runFirst_sys_an_tagCh_msecWait;
    private runFirst_sys_an_tagCh_msecWait_Kidoku;
    private runFirst_sys_an_auto_msecPageWait;
    private runFirst_sys_an_auto_msecLineWait;
    private runFirst_Bool_hSaveVal_true;
    private runFirst_Bool_hTmp_true;
    private runFirst_Bool_hTmp_false;
}
